# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c5ae63266e01ef85989f968d5b066e50f5e543904f77cf00e0209c6f8cb05a31d24eecb759819cdc5b5dae8174bcd02b5c894d5ccf66bbfacda2929043cc22

test:
  secret_key_base: 4aa1162cc5155040bfb2c97e31c7faa43d4a46849e2f3c35ed8267de75a71dc5297f28b493bb74d3df765ab0577afcc49ff41939906713fc989bc30de372c9cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
