# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b14f5ef6713a096dd89791e993673a0bd4127097bfb7e6268fff1a4bcbaa192bda75bb82a8588981fdd89ae686ab93b516de56d483d09cd99e2db496b422eb42

test:
  secret_key_base: 8c7d73a79358bda5982f78b575082101d449f6da32f1b100d2496a2c79fa12803c497d3ac3a7fcbe9c9ffcd77116fe15bc06d1474262589d91bcbcd922fddb6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
